LU_Tester.exe: LU.o LU_Tester.o
	gcc -o LU_Tester.exe LU.o LU_Tester.o

LU.o: LU.c
	gcc -ansi -pedantic -Wall -Werror -c LU.c

LU_Tester.o: LU_Tester.c
	gcc -ansi -pedantic -Wall -Werror -c LU_Tester.c

