GaussJordan_Tester.exe: GaussJordan.o GaussJordan_Tester.o
	gcc -o GaussJordan_Tester.exe GaussJordan.o GaussJordan_Tester.o

GaussJordan.o: GaussJordan.c
	gcc -ansi -pedantic -Wall -Werror -c GaussJordan.c

GaussJordan_Tester.o: GaussJordan_Tester.c
	gcc -ansi -pedantic -Wall -Werror -c GaussJordan_Tester.c

