QueueDBA_Tester.exe: QueueDBA.o QueueDBA_Tester.o
	gcc -o QueueDBA_Tester.exe QueueDBA.o QueueDBA_Tester.o

QueueDBA.o: QueueDBA.c
	gcc -ansi -pedantic -Wall -Werror -c QueueDBA.c

QueueDBA_Tester.o: QueueDBA_Tester.c
	gcc -ansi -pedantic -Wall -Werror -c QueueDBA_Tester.c

